#name: my-dev-vault-cluster

services:
  vault-server1:
    image: hashicorp/vault:1.19
    hostname:  vault-dev-server1
    container_name: vault-dev-server1
    # ports:
    #   - "8206:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://localhost:8200

    volumes:
    #  - ./vault-server1/file:/vault/file # mapping storage volume on computer
      - vault1-raftstorage:/vault/file
      - ./vault-server1/logs:/vault/logs # mapping storage volume on computer
      - ./vault-server1/config:/vault/config # mapping storage volume on computer
      - ./unseal-script:/unseal-script
    # entrypoint: vault server -config=/vault/config/config.hcl
    entrypoint: ["/bin/sh", "-c", "/unseal-script/vault-init.sh && tail -f /dev/null"]
    

  vault-server2:
    image: hashicorp/vault:1.19
    hostname:  vault-dev-server2
    container_name: vault-dev-server2
    # ports:
    #   - "8202:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://localhost:8200

    volumes:
   #   - ./vault-server2/file:/vault/file # mapping storage volume on computer
      - vault2-raftstorage:/vault/file
      - ./vault-server2/logs:/vault/logs # mapping storage volume on computer
      - ./vault-server2/config:/vault/config # mapping storage volume on computer
      - ./unseal-script:/unseal-script
   # entrypoint: vault server -config=/vault/config/config.hcl
    entrypoint: ["/bin/sh", "-c", "/unseal-script/vault-raft-join.sh && tail -f /dev/null"]
    depends_on:
      - vault-server1

  vault-server3:
    image: hashicorp/vault:1.19
    hostname:  vault-dev-server3
    container_name: vault-dev-server3
    # ports:
      # - "8204:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://localhost:8200
    volumes:
   #   - ./vault-server3/file:/vault/file # mapping storage volume on computer
      - vault3-raftstorage:/vault/file
      - ./vault-server3/logs:/vault/logs # mapping storage volume on computer
      - ./vault-server3/config:/vault/config # mapping storage volume on computer
      - ./unseal-script:/unseal-script
   # entrypoint: vault server -config=/vault/config/config.hcl
    entrypoint: ["/bin/sh", "-c", "/unseal-script/vault-raft-join.sh && tail -f /dev/null"]
    depends_on:
      - vault-server1
      - vault-server2

  load-balancer:
    image: nginx
    container_name: nginx_load_balancer
    volumes:
      - ./load-balancer/config/nginx.conf:/etc/nginx/conf.d/nginx.conf  # Map the custom config
      - ./load-balancer/certs:/etc/nginx/certs:ro   #Docker Compose will mount them inside Nginx
      - ./load-balancer/logs:/var/log/nginx

    ports:
      # - "9090:80"
      - "9443:443"
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80
    networks:
      - vault-cluster-network
    depends_on:
      - vault-server1
      - vault-server2
      - vault-server3

networks:
  vault-cluster-network:
    driver: bridge
   # external: true
   # name: vault-cluster-network

volumes:
  vault1-raftstorage:
  vault2-raftstorage:
  vault3-raftstorage:


